### PR TITLE
Athletics updated

### PR DESCRIPTION
**Pull request by Ginzura**
Unlike last year, one track event markdown file contains all of the track events. The same has been done with field events.

### CODE REVIEW

**Comment by mbrn-in** [comment]
Hi @Ginzura.

Did you check the deploy preview link?

Did you check whether the events that you added are rightly appearing in search results and in the expected URLs?

**Comment by Ginzura** [comment]
Yes sir.

**Comment by Ginzura** [comment]
> Hi @Ginzura.
> 
> Did you check the deploy preview link?
> 
> Did you check whether the events that you added are rightly appearing in search results and in the expected URLs?

YES Brother.

**Comment by mbrn-in** [comment]
Website, should get updated right now!

**Comment by mbrn-in** [comment]
Check out and let me know if there are any issues.

**Pull request merged**
